###############################################################################
# 
# Backgrounds
#
# image bg  = "images/bg/.jpg"
#
#

# Grandes BGs

image bg home_a = "images/bg/home_a.jpg"
image bg home_b = "images/bg/home_b.jpg"
image bg home_c = "images/bg/home_c.jpg"
image bg center_a = "images/bg/center_a.jpg"
image bg center_b = "images/bg/center_b.jpg"
image bg center_c = "images/bg/center_c.jpg"
image bg station_a = "images/bg/station_a.jpg"
image bg station_b = "images/bg/station_b.jpg"
image bg station_c = "images/bg/station_c.jpg"
image bg suburbs_a = "images/bg/suburbs_a.jpg"
image bg suburbs_b = "images/bg/suburbs_b.jpg"
image bg suburbs_c = "images/bg/suburbs_c.jpg"


# Outros BGs

image bg arcade = "images/bg/arcade.jpg"
image bg bathhouse_a = "images/bg/bathhouse_a.jpg"
image bg bathhouse_c = "images/bg/bathhouse_c.jpg"
image bg beach_a = "images/bg/beach_a.jpg"
image bg beach_b = "images/bg/beach_b.jpg"
image bg beach_c = "images/bg/beach_c.jpg"
image bg brothel = "images/bg/brothel.jpg"
image bg cafeteria = "images/bg/cafeteria.jpg"
image bg changing_room = "images/bg/changing_room.jpg"
image bg church_a = "images/bg/church_a.jpg"
image bg church_b = "images/bg/church_b.jpg"
image bg church_c = "images/bg/church_c.jpg"
image bg class_a = "images/bg/class_a.jpg"
image bg class_b = "images/bg/class_b.jpg"
image bg class_c = "images/bg/class_c.jpg"
image bg computer = "images/bg/computer.jpg"
image bg conven_a = "images/bg/conven_a.jpg"
image bg conven_b = "images/bg/conven_b.jpg"
image bg conven_c = "images/bg/conven_c.jpg"
image bg dinner_a = "images/bg/dinner_a.jpg"
image bg dinner_b = "images/bg/dinner_b.jpg"
image bg dinner_c = "images/bg/dinner_c.jpg"
image bg dorms = "images/bg/dorms.jpg"
image bg gym = "images/bg/gym.jpg"
image bg gymdepo = "images/bg/gymdepo.jpg"
image bg hosp_a = "images/bg/hospital_a.jpg"
image bg hosp_b = "images/bg/hospital_b.jpg"
image bg hosp_c = "images/bg/hospital_c.jpg"
image bg infirmary_a = "images/bg/infirmary_a.jpg"
image bg infirmary_b = "images/bg/infirmary_b.jpg"
image bg infirmary_c = "images/bg/infirmary_c.jpg"
image bg inn_a = "images/bg/inn_a.jpg"
image bg inn_b = "images/bg/inn_b.jpg"
image bg inn_c = "images/bg/inn_c.jpg"
image bg library = "images/bg/library.jpg"
image bg maidcafe = "images/bg/maidcafe.jpg"
image bg motel = "images/bg/motel.jpg"
image bg mountains_a = "images/bg/mountains_a.jpg"
image bg mountains_b = "images/bg/mountains_b.jpg"
image bg mountains_c = "images/bg/mountains_c.jpg"
image bg office_a = "images/bg/office_a.jpg"
image bg office_b = "images/bg/office_b.jpg"
image bg office_c = "images/bg/office_c.jpg"
image bg office_job = "images/bg/office_job.jpg"
image bg office_jobi = "images/bg/office_jobi.jpg"
image bg onsen_a = "images/bg/onsen_a.jpg"
image bg onsen_b = "images/bg/onsen_b.jpg"
image bg onsen_c = "images/bg/onsen_c.jpg"
image bg park_a = "images/bg/park_a.jpg"
image bg park_b = "images/bg/park_b.jpg"
image bg park_c = "images/bg/park_c.jpg"
image bg playg_a = "images/bg/playg_a.jpg"
image bg playg_b = "images/bg/playg_b.jpg"
image bg playg_c = "images/bg/playg_c.jpg"
image bg pub = "images/bg/pub.jpg"
image bg restau_1 = "images/bg/restau_1.jpg"
image bg rural_a = "images/bg/rural_a.jpg"
image bg rural_b = "images/bg/rural_b.jpg"
image bg rural_c = "images/bg/rural_c.jpg"
image bg school_a = "images/bg/school_a.jpg"
image bg school_b = "images/bg/school_b.jpg"
image bg school_c = "images/bg/school_c.jpg"
image bg school_gym = "images/bg/school_gym.jpg"
image bg school_lab = "images/bg/school_lab.jpg"
image bg school_pool = "images/bg/school_pool.jpg"
image bg school_roof_a = "images/bg/school_roof_a.jpg"
image bg school_roof_b = "images/bg/school_roof_b.jpg"
image bg school_roof_c = "images/bg/school_roof_c.jpg"
image bg shopping = "images/bg/shopping.jpg"
image bg sport_a = "images/bg/sport_a.jpg"
image bg sport_b = "images/bg/sport_b.jpg"
image bg sport_c = "images/bg/sport_c.jpg"
image bg shrine_a = "images/bg/shrine_a.jpg"
image bg shrine_b = "images/bg/shrine_b.jpg"
image bg shrine_c = "images/bg/shrine_c.jpg"
image bg train_a = "images/bg/train_a.jpg"
image bg train_b = "images/bg/train_b.jpg"
image bg train_c = "images/bg/train_c.jpg"
image bg underworld = "images/bg/underworld.jpg"
image bg underworld_store = "images/bg/underworld_store.jpg"

image bg  = "images/bg/.jpg"
image bg  = "images/bg/.jpg"
image bg  = "images/bg/.jpg"
image bg  = "images/bg/.jpg"
image bg  = "images/bg/.jpg"
image bg  = "images/bg/.jpg"

